services:
    _defaults:
        autoconfigure: true

    contao_file_usage.file_usage_cache:
        class: Symfony\Component\Cache\Adapter\FilesystemAdapter
        arguments: ['fileusage', 86400, '%kernel.cache_dir%']

    contao_file_usage.finder.file_usage:
        class: InspiredMinds\ContaoFileUsage\Finder\FileUsageFinder
        public: true
        arguments:
            - '@contao.framework'
            - '@contao_file_usage.file_usage_cache'
            - !tagged_iterator { tag: contao_file_usage.provider }

    contao_file_usage.console.file_usage_warmup:
        class: InspiredMinds\ContaoFileUsage\Console\FileUsageWarmupCommand
        arguments:
            - '@contao_file_usage.finder.file_usage'

    InspiredMinds\ContaoFileUsage\Controller\ReplaceFileReferencesController:
        arguments:
            - '@twig'
            - '@contao.framework'
            - '@translator'
            - '@router'
            - '@contao_file_usage.finder.file_usage'
            - '@contao_file_usage.replace.file_reference'
            - '@contao_file_usage.file_usage_cache'
            - '@contao_file_usage.result.result_enhancer'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'
        tags: ['controller.service_arguments']

    InspiredMinds\ContaoFileUsage\Controller\ShowFileReferencesController:
        arguments:
            - '@twig'
            - '@contao.framework'
            - '@contao_file_usage.finder.file_usage'
            - '@contao_file_usage.result.result_enhancer'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'
        tags: ['controller.service_arguments']

    contao_file_usage.cron.build_cache:
        class: InspiredMinds\ContaoFileUsage\Cron\BuildCacheCronJob
        arguments:
            - '@contao_file_usage.finder.file_usage' 

    contao_file_usage.event_listener.backend_menu:
        class: InspiredMinds\ContaoFileUsage\EventListener\BackendMenuListener
        arguments:
            - '@request_stack'
        tags: ['kernel.event_listener']

    contao_file_usage.event_listener.data_container_show.show_references_button:
        class: InspiredMinds\ContaoFileUsage\EventListener\DataContainer\ShowReferencesButtonCallback
        arguments:
            - '@router'
            - '@contao_file_usage.file_usage_cache'
            - '@translator'
        tags: 
            - { name: contao.callback, table: tl_files, target: list.operations.fileusage.button }

    contao_file_usage.maintenance.clear_file_usage_cache:
        class: InspiredMinds\ContaoFileUsage\Maintenance\ClearFileUsageCache
        public: true
        arguments: 
            - '@contao_file_usage.file_usage_cache'

    contao_file_usage.provider.database_insert_tag:
        class: InspiredMinds\ContaoFileUsage\Provider\DatabaseInsertTagProvider
        arguments:
            - '@database_connection'

    contao_file_usage.provider.file_tree:
        class: InspiredMinds\ContaoFileUsage\Provider\FileTreeProvider
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@contao.resource_finder'

    contao_file_usage.replace.file_reference:
        class: InspiredMinds\ContaoFileUsage\Replace\FileReferenceReplacer
        arguments:
            - '@database_connection'
            - '@contao.framework'

    contao_file_usage.result.result_enhancer:
        class: InspiredMinds\ContaoFileUsage\Result\ResultEnhancer
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@router'
            - '@request_stack'
            - '@contao.csrf.token_manager'
            - '%contao.csrf_token_name%'

    InspiredMinds\ContaoFileUsage\Finder\FileUsageFinderInterface: '@contao_file_usage.finder.file_usage'
    InspiredMinds\ContaoFileUsage\Replace\FileReferenceReplacerInterface: '@contao_file_usage.replace.file_reference'
    InspiredMinds\ContaoFileUsage\Replace\ResultEnhancerInterface: '@contao_file_usage.result.result_enhancer'
